# Generated by Django 6.0.7 on 2026-07-08 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('completed', 'Completed')], default='pending_review', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='expenses.group')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=3)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exchange_rate_used', models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ('converted_inr_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('split_type', models.CharField(choices=[('equal', 'Equal'), ('exact', 'Exact amount'), ('percentage', 'Percentage'), ('share', 'Share (weighted units)'), ('unequal', 'Unequal (explicit per-person amount)')], max_length=20)),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_paid', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expenses.group')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_paid', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='expenses.group')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='expenses.importbatch')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100)),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('share_input', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='expenses.expense')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('guest_name', ''), _negated=True), _connector='OR'), name='participant_has_user_or_guest_name')],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField()),
                ('left_at', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='expenses.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['group', 'user', 'joined_at'], name='expenses_gr_group_i_e94d2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('issue_type', models.CharField(choices=[('duplicate', 'Duplicate expense'), ('conflicting_duplicate', 'Duplicate with differing amount'), ('settlement_as_expense', 'Settlement logged as expense'), ('negative_amount', 'Negative amount'), ('malformed_amount', 'Malformed amount'), ('zero_amount', 'Zero amount'), ('missing_payer', 'Missing payer'), ('unresolved_name', 'Payer/participant name could not be matched'), ('missing_currency', 'Missing currency'), ('invalid_date', 'Corrupted or implausible date'), ('ambiguous_date', 'Ambiguous date format'), ('non_member_participant', 'Participant is not a group member'), ('membership_mismatch', 'Participant not active member on expense date'), ('split_percentage_invalid', 'Percentages do not sum to 100'), ('split_type_mismatch', 'Split type label contradicts supplied share data'), ('other', 'Other')], max_length=40)),
                ('severity', models.CharField(choices=[('blocking', 'Blocking'), ('warning', 'Warning')], max_length=10)),
                ('description', models.TextField()),
                ('suggested_action', models.TextField(blank=True)),
                ('chosen_action', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('resolved', 'Resolved'), ('rejected', 'Row rejected, not imported')], default='pending', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='expenses.importbatch')),
            ],
            options={
                'verbose_name_plural': 'import anomalies',
                'indexes': [models.Index(fields=['import_batch', 'status'], name='expenses_im_import__1ff51e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['group', 'date'], name='expenses_ex_group_i_f6bb8c_idx'),
        ),
    ]
